feat: support slash inline command
hyperqueryhq/rich-markdown-editor pull request #33
Opened 2022-04-15 11:46 UTC by duongtn811

## Issues
- Support inline slash

## Loom video

https://www.loom.com/share/23c753dbad4f4384b5f7f1ea3b86d848

2022-04-15 16:52 UTC, damianrodrigues requested changes
https://www.loom.com/share/c1125298cdec4fac96d4bb6048d06372

2022-04-18 05:55 UTC, duongtn811 commented
Hi @hoantran-it @damianrodrigues 
I have fixed the comments. could you help review it again?

2022-04-18 14:43 UTC, duongtn811 commented
The loom to explain my fix
https://www.loom.com/share/ca2b2ddf6463494982a6c97f3ce0fb9c

2022-04-18 18:24 UTC, damianrodrigues requested changes
Amazing work, just a few nits

2022-04-18 18:24 UTC, damianrodrigues commented on src/plugins/BlockMenuTrigger.tsx
> +  const currentText = state.selection.$from.parent.content?.content?.[0].text;
Can we clarify what is [0]? Either you can use array destructuring and give a descriptive variable name or put a comment explaining what this is

2022-04-18 18:24 UTC, damianrodrigues commented on src/plugins/BlockMenuTrigger.tsx
> +              );
Same comment as the above

2022-04-18 18:24 UTC, damianrodrigues commented on src/plugins/BlockMenuTrigger.tsx
> +                );
This part is a bit confusing, we are expecting to run the function and return null or then run another function and also can return null? Would it be possible to unify this into one function?

2022-04-18 18:24 UTC, damianrodrigues commented on src/plugins/BlockMenuTrigger.tsx
> +                      this.options.onOpen(match[3]);
Let's use constants to clarify what's the number `3` here

2022-04-18 18:24 UTC, damianrodrigues commented on src/components/BlockMenu.tsx
> +    const offset = state.tr.selection.anchor + 1;
What's `1` here, let's use a constant or put a comment explaining what's this

2022-04-18 18:24 UTC, damianrodrigues commented on src/components/BlockMenu.tsx
> +        parent.pos + lastSlashIndex + 1,
What's `1`? Let's use a constant or a comment explaining this

2022-04-19 02:48 UTC, duongtn811 commented on src/plugins/BlockMenuTrigger.tsx
> +  const currentText = state.selection.$from.parent.content?.content?.[0].text;
![Screen Shot 2022-04-19 at 09 47 48](https://user-images.githubusercontent.com/11365903/163910234-b39cc9db-bb31-4d95-9c4a-d47b0fc1fa54.png)

actually, it's the structure of a content inside a node. I am not sure why there always is one TextContent but it's an array

2022-04-19 16:19 UTC, duongtn811 commented
Hello @damianrodrigues 
I have refactored to have better code and also comment on some points to explain my work. Could you please help take a look again?

2022-04-21 19:08 UTC, damianrodrigues approved these changes
LGTM!

2022-04-21 19:09 UTC, merged